my task 0x05. Python - Exceptions
